[package]
name = "moneyman_core"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
bytes = { workspace = true }
zip = { workspace = true }
rusty-money = { workspace = true }
polars = { workspace = true }
