[package]
name = "moneyman_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
moneyman_core = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
zip = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = "0.8"
