[package]
name = "moneyman_cli"
description = "A simple CLI for currency conversion"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
# documentation.workspace = true

[dependencies]
moneyman = { workspace = true, features = ["time"], default-features = false }
rusty-money = { workspace = true }
time = { workspace = true, features = ["serde"] }
rust_decimal = { workspace = true }
dirs = { workspace = true }
clap = { workspace = true }
serde.workspace = true

[[bin]]
name = "moneyman"
path = "src/main.rs"
