name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup nix
      uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          store = /home/runner/nix
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://cache.nixos.org/

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: /home/runner/nix
        key: ${{ runner.os }}-${{ hashFiles('flake.lock') }}

    - name: Run tests
      run: nix develop .#devShells.x86_64-linux.ci --command bash -c "cargo test"

    - name: Build
      run: nix build .#packages.x86_64-linux.moneyman

    - name: Formatting
      run: nix develop .#devShells.x86_64-linux.ci --command bash -c "rustfmt --check crates/**/src/*"

    - name: Clippy, the final gatekeeper
      run: nix develop .#devShells.x86_64-linux.ci --command bash -c "cargo clippy -- -Dwarnings"

