[package]
name = "moneyman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moneyman_core = { workspace = true }
rusty-money = { workspace = true }
chrono = { workspace = true }
